default: &default
  adapter: postgresql
  encoding: unicode
  database: regional_archive_dev
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

production:
  <<: *default